image: node:8.4.0

stages:
  - lint
  - test
  - dockerize
  - deploy

lint:
  stage: lint
  script:
  - npm run lint

test:
  stage: test
  script:
  - npm install -g mocha
  - npm install
  - npm test

build_image:
  stage: dockerize
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u $CI_BUILD_LOGIN -p $CI_BUILD_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/libs/registry .
    - docker push registry.gitlab.com/libs/registry
  only:
    - develop


